name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write # Required for npm provenance
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Extract version info
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "Publishing release: ${{ github.event.release.tag_name }}"
            echo "Release name: ${{ github.event.release.name }}"
            # Extract version from tag and update package.json for build
            TAG_NAME="${{ github.event.release.tag_name }}"
            VERSION=${TAG_NAME#v}
            echo "Extracted version: $VERSION"
            npm version $VERSION --no-git-tag-version
          else
            echo "Manual workflow dispatch - using current package.json version"
          fi
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Build package
        run: bun run build
        
      - name: Verify build output
        run: |
          ls -la dist/
          echo "Checking package.json exports..."
          cat package.json | grep -A 20 "exports"
        
      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
