name: Release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Extract version from tag
        run: |
          # Extract version from the release tag (remove 'v' prefix if present)
          TAG_NAME="${{ github.event.release.tag_name }}"
          VERSION=${TAG_NAME#v}
          echo "Release tag: $TAG_NAME"
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Update package.json version
        run: |
          # Update package.json with the release version
          npm version ${{ env.VERSION }} --no-git-tag-version
          echo "Updated package.json to version ${{ env.VERSION }}"
          
      - name: Commit version update
        run: |
          git add package.json
          if git diff --staged --quiet; then
            echo "No changes to package.json"
          else
            git commit -m "chore: update package.json version to v${{ env.VERSION }}"
            git push origin main
            echo "Updated package.json version and pushed to main"
          fi
